# Generated by Django 2.1 on 2018-10-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='by',
            name='product_name',
        ),
    ]
