# Generated by Django 2.1 on 2018-10-20 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('Buy', '0002_remove_by_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='by',
            name='product_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.PROD'),
        ),
    ]
