# Generated by Django 2.1 on 2018-10-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Disc', models.CharField(max_length=400)),
                ('Body', models.TextField()),
                ('pic', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('slug1', models.SlugField()),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
    ]
